previewsEnabled: true
previewsExpireAfterDays: 1
services:
  - type: web
    name: api
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    repo: 'https://github.com/sergeylukin/justt-another-assignment-solution.git'
    dockerCommand: ./apps/api/entrypoint.sh
    healthCheckPath: /api
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_HOST
        value: 0.0.0.0
      - key: DB_HOST
        fromDatabase:
          name: justt-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: justt-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: justt-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: justt-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: justt-db
          property: database
  - type: web
    name: app
    env: static
    buildCommand: 'npm run build:web'
    staticPublishPath: ./dist/apps/front-website
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    envVars:
      - key: NODE_VERSION
        value: 14.5.0
      - key: NODE_ENV
        value: production
      - key: API_HOST
        fromService:
          type: web
          name: api
          property: host
      - key: API_PORT
        fromService:
          type: web
          name: api
          property: port
    routes:
      - type: rewrite
        source: /api
        destination: 'https://api-127p.onrender.com/api/'
      - type: rewrite
        source: /api/
        destination: 'https://api-127p.onrender.com/api/'
      - type: rewrite
        source: /api/*
        destination: 'https://api-127p.onrender.com/api/*'
databases:
  - name: justt-db
    databaseName: justt
    ipAllowList: []
    plan: starter
    previewPlan: starter
    postgresMajorVersion: 14

