version: '3.4'

x-healthcheck-defaults: &default-healthchecks
  interval: 30s
  timeout: 10s
  retries: 3

x-justt-volumes: &justt-volumes
  - ./:/usr/app
  - /usr/app/node_modules

services:
  api:
    build:
      context: ./
      target: development
      dockerfile: ./apps/api/Dockerfile
    command: ["./scripts/wait-for-it.sh", "${DB_HOST}:${DB_PORT}", "--", "./scripts/docker-api-dev.sh", "${DATABASE_URL}"]
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      *justt-volumes
    ports:
      - '3333:3333'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3333']
      <<: *default-healthchecks

  app:
    build:
      context: ./
      target: builder
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/front-website/Dockerfile
    volumes:
      *justt-volumes
    ports:
      - 4200:4200
    command: ["npm", "run", "serve:web"]
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4200']
      <<: *default-healthchecks

  postgres:
    image: postgres:14-alpine
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
